feat: partially support for local Node.js packages analysis
ossillate-inc/packj pull request #33
Opened 2023-03-05 15:45 UTC by werifu

I improved the packj to partially support the analysis for local Node.js packages.
Usage: replace original `npm:xxx` with `local_node:/path/to/xxx`, relative path is also ok.

It works, but just works.
**Partially support**, means that not all original features supported. Local packages do not have too many metadata, therefore it's hard to apply meta analysis...

![image](https://user-images.githubusercontent.com/53432474/222970223-e2c7eb63-5ce4-4372-8d49-787c6144d7ac.png)

captured project is from
https://github.com/microsoft/vscode-extension-samples/tree/main/custom-editor-sample

2023-03-07 11:49 UTC, ashishbijlani commented on packj/audit/main.py
> +		elif pm_name == 'npm' or pm_name == 'local_node':
Minor nitpick: `local_nodejs` is more descriptive.

2023-03-07 11:55 UTC, ashishbijlani requested changes

2023-03-07 11:55 UTC, ashishbijlani commented on packj/audit/main.py
> +		elif pm_name == 'npm' or pm_name == 'local_node':
Minor nitpick: `local_nodejs` is more descriptive.

2023-03-07 11:55 UTC, ashishbijlani commented on packj/audit/pm_proxy/local_node.py
> +class LocalNodeProxy(PackageManagerProxy):
Same: `LocalNodeJSProxy`

2023-03-07 11:55 UTC, ashishbijlani commented on packj/audit/pm_proxy/npmjs.py
> -		assert pkg_info and 'versions' in pkg_info, "package not found!"
Why remove the `assert` statement?

2023-03-07 11:55 UTC, ashishbijlani commented on packj/audit/pm_util.py
> +		return PackageManagerEnum.local_node
`local_nodejs`

2023-03-07 11:55 UTC, ashishbijlani commented on packj/util/enum_util.py
> +    local_node = 'local_node'
`local_nodejs`

2023-03-08 04:37 UTC, werifu commented
I have fixed all problems you mentioned above at [6cb5c5a](https://github.com/ossillate-inc/packj/pull/33/commits/6cb5c5a99db467498c4e26f61c503771f961235f) as well as some original minor bugs

2023-03-08 04:39 UTC, werifu commented on packj/audit/pm_proxy/npmjs.py
> -		assert pkg_info and 'versions' in pkg_info, "package not found!"
Deleted by mistake, I have recovered.

2023-03-08 21:31 UTC, ashishbijlani approved these changes

2023-03-08 21:34 UTC, merged

2023-03-18 14:41 UTC, Roviky commented
i find that Local packages is hard to apply meta analysis too!!!!!!