Adds npm confusion
ossillate-inc/packj pull request #66
Opened 2023-07-05 03:49 UTC by shivaabhishek07

2023-07-07 02:25 UTC, ashishbijlani requested changes
NPM-specific changes must go in NPM proxy class.

2023-07-07 02:25 UTC, ashishbijlani commented on packj/audit/main.py
> +                    metadata_url = "https://registry.npmjs.org/%s/%s" % (pkg_name, ver_str)
This looks like NPM-specific and must go under NPM proxy class.

2023-07-08 14:56 UTC, shivaabhishek07 commented
Also forgot to mention that when you run `python3 main.py audit -p npm:<package_name>`, this manifest confusion will download a package at the root level or from where you run `python3...`.
When I try to store them in `/tmp` file, I cannot access it, It shows some error. That's the reason I made it to download at the folder or location where this is being run...

2023-08-09 05:04 UTC, ashishbijlani approved these changes

2023-08-09 05:04 UTC, merged